name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: appleboy/telegram-action@master
     - name: send photo message
       with:
        to: 645608999
        token: 6761703468:AAHNSgi351xeIVjjLLB52oHmGMZy5KkJEn8
        message: send photo message
        photo: msg645608999-11097.jpg
